### ISSUE TITLE
Compatibility with the N0100

### ISSUE THREAD

**Issue by LeGmask** [zardam/nw-external-apps#2]
Yop,

Any way to add compatibility to the N0100 ?

**Comment by zardam** [comment]
The flash is too small on the N0100 to be useful with this tool. You can still install Omega firmware (https://github.com/Omega-Numworks/Omega) and/or the NES emulator (https://github.com/zardam/numworks-nofrendo).

It is also possible to solder a flash chip on the N0100 to have more memory. Delta firmware with KhiCAS (https://github.com/delta-Numworks/delta) is working on a modified N0100.

**Comment by LeGmask** [comment]
Hmm and if I modify my n0100, this should work ?

**Comment by zardam** [comment]
Yes, but be prepared to build the firmware yourself, as the ones provided on this page will only work on a n0110.
